#define ZX_SPLASH_CODE_ROM_ADDR 0x3f00
#define ZX_SPLASH_PARAM1_ROM_ADDR 0x3f04

#define ZX_SPLASH_ROMREAD_START_BORDER  3
#define ZX_SPLASH_ROMREAD_END_BORDER    4

#define ZX_SPLASH_CODE_BOOT 0
#define ZX_SPLASH_CODE_UNSUPPORTED_ATA_COMMAND 1
#define ZX_SPLASH_CODE_UNSUPPORTED_SECTOR_COUNT 2
#define ZX_SPLASH_CODE_PORT_READ 3
#define ZX_SPLASH_CODE_PORT_WRITE 4
